[build]
  publish = "site"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/wp-admin/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/wp-login.php"
  to = "/"
  status = 301
